### PR TITLE
Create images

### PR DESCRIPTION
**Pull request by farhanajuli**
bankCardLogo1

bankCardLogo2

bankCardLogo2

### CODE REVIEW

**Comment by Pritam-2002** [comment]
@farhanajuli i think it will be good if we make the logo text based...??

**Comment by farhanajuli** [comment]
@Pritam-2002  if you have any specific idea, then please share that with us

**Comment by farhanajuli** [comment]
@Pritam-2002  check the last one, I think this will go like butter in our website.

**Comment by Pritam-2002** [comment]
@farhanajuli can you give a screenshot how it is looking
?

**Comment by tamalchowdhury** [comment]
Thanks @farhanajuli for the logo designs!

**Comment by farhanajuli** [comment]
> @farhanajuli can you give a screenshot how it is looking ?

it's already given in the comment

**Pull request merged**
