### PR TITLE
add the logos of the bank before the name....

### PR DESCRIPTION
**Pull request by Pritam-2002**
added the logos of the bank before their name....please review  and check the changes ...
bank logo

### CODE REVIEW

**Comment by Pritam-2002** [comment]
@tamalchowdhury please review my code..i had make some changes

**Comment by tamalchowdhury** [comment]
Hi @Pritam-2002, it would be great if we host these images on the site and not hot linking to 3rd party services. This will make multiple requests and impact the load time. 

Please make a new directory `/img`. Then download all the images in that directory and then link them from the site.

You have to add another commit and it will add to this PR.

Thanks!

**Comment by Pritam-2002** [comment]
Ok on it

**Comment by Pritam-2002** [comment]
@tamalchowdhury i had make the necessary changes please review it....

**Comment by tamalchowdhury** [comment]
Hi @Pritam-2002, just one more change and it will be good to go:

Change the directory name from `/table-Images` to just `/img` (remember, we should not have uppercase/lowercase mix in directory names.

Tip: You can search and replace the name and links in VS Code. You can search all, and replace all.

The same goes for the file names. Kindly rename all the file names to be more uniform:

```
brac-bank.png
city-bank.png
bank-asia.png
eastern-bank.jpg
```
..and so on. All lowercase, no space, and consistent naming scheme.

Thank you for your patience 😊

**Comment by Pritam-2002** [comment]
i need to change the images name ....i will change it in few minutes

**Comment by Pritam-2002** [comment]
@tamalchowdhury do i change the images name with their specific bank name with no space or i rename them with img-1 ,img-2 in such way??

**Comment by Pritam-2002** [comment]
@tamalchowdhury i had made the changes please review it .....

**Review by tamalchowdhury — APPROVED** [review]

**Pull request merged**
